name: Code Review
on:
  pull_request:
    branches:
      - main
      - int
permissions:
  contents: read

jobs:
  code-review:
    name: Code Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Code Review
        uses: docker://ghcr.io/step-security/code-reviewer/int:latest
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
